<?php

namespace CCC\EmailTemplateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateRepository extends EntityRepository
{
}
